### ISSUE TITLE
On Close, write dots to temporary layers

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/Dotter#1]
One per instance, using settings in the instance custom parameters

**Comment by jvgaultney** [comment]
It might be better to have Pendot Designer as a plugin that could be opened and remain open, and can write to layers that remain in the project, and would be updated if they already exist. I can easily see this workflow:

- Open tool
- Toggle UI control to either use instance custom parameters or ones set in UI fields
- Set layer name suffix (with reasonable default)
- Press Apply
- Look through layers and glyphs to review
- Tweak parameters either in instance or in the still open plugin UI
- Press Apply, review again, tweak...
- Close UI when done

In general, closing a filter or plugin should not be a substitute for an Apply button.

**Comment by jvgaultney** [comment]
There are two other related issues:

The modal nature of the UI means that once you activate it you can't move around in the preview window. So you need to set up what you want to see in the window, then activate the plugin, but then you can't see anything else. You need to close the plugin and repeat, which is a pain.

Currently when you activate the plugin it immediately applies whatever settings were last used. Even for only 26 letters that can take 3-10 seconds, then every time you change a single parameter it recalculates again. The live nature of this is cool if you're looking only at a single glyph, but if you've selected 20+ glyphs it gets in the way. It would be better if the plugin didn't apply anything until you hit an Apply button. Some delay, especially for a large number of selected glyphs, is expected but it should happen only when you want it to.

**Comment by simoncozens** [comment]
> The modal nature of the UI means that once you activate it you can't move around in the preview window. So you need to set up what you want to see in the window, then activate the plugin, but then you can't see anything else. You need to close the plugin and repeat, which is a pain.

This sadly appears to be the nature of GlyphsApp filters; the other filters (try Noodler) behaves the same. You should be able to zoom in and out, though. Apparently we can have a non-modal interface with a vanilla-based plugin instead of a filter, and maybe this is where we need to go because we are starting to do a lot of things that don't really fit the "filter" model anyway.

**Comment by simoncozens** [comment]
OK, this is (I think) done, at least from the UI side. (Build side to follow.) Now we are both a reporter and a *script*, I'm going to add a readme to help with installation etc. - and @jvgaultney, you will need to make changes to your installation to get it working again. I'll document all that.
