### ISSUE TITLE
Improve dotting at tight corners

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#12]
One of the most problematic situations for dotting is at sharp corners with tight angles. It's not clear how to improve these by manipulating the outline:

![image](https://github.com/simoncozens/Dotter/assets/4226750/a8228f81-c4eb-4d65-b060-115d3f3df6d9)

(font-pendot-latin size/spacing 60/40 with prevent overlap and split paths)

These examples are much better than some others, and have forced dots at all sharp corners of AVW. This helps with aligning dots to the baseline or cap height (but the top of A is still too low), but often there is a gap after the forced dot. It seems like the segment(s) connecting to sharp corners need some realignment to fill in the gap.

**Comment by simoncozens** [comment]
I believe this is now fixed.
