### ISSUE TITLE
Designer crashes on Intel

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#13]
The addition of stoking to Designer causes it to crash, which looks like a problem on Intel architectures.

![image](https://github.com/simoncozens/Dotter/assets/4226750/db76e161-b6fc-4575-a35a-f2313285e9ac)

Our team is half Intel machines and half Apple Silicon so needs to run on both.

**Comment by simoncozens** [comment]
OK, that's my fault. I added stroking, and I need to check that the Rust-based stroker module has both Intel and Apple Silicon architectures in it.

**Comment by jvgaultney** [comment]
Works fine on my Apple Silicon one though - very nice! (I have both for this sort of testing)

**Comment by simoncozens** [comment]
Should be fixed now - pull again and restart.

**Comment by simoncozens** [comment]
(I'm running it on Intel now, the question is whether or not I broke it on Apple Silicon. ;-)

**Comment by simoncozens** [comment]
WFM on Apple Silicon.

**Comment by jvgaultney** [comment]
Works for me on Intel - will check Apple Silicon
