### ISSUE TITLE
'Pendot Quick Preview' layer keeps sneaking in

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#17]
The 'Pendot Quick Preview' layer is a remnant from an old version of Dotter, however editing in Glyphs with the Pendot Designer script active sometimes adds this layer back into the primary master. This occurs even after the layer has been completely removed from all glyphs with a script and the layer confirmed to be eliminated from the .glyphspackage file.

Steps to reproduce:

- open PendotLSource, go to tab with abcdefgh... and 'e' in focus
- run Pendot Designer
- click on Regular in the list of Layers in the Glyphs right side panel
- the windows changes to show the skeleton, but the Pendot Quick Preview layer suddenly appears again

**Comment by simoncozens** [comment]
I'm not sure this is right. The Quick Preview layer is still in use - it's what produces the live previews for each glyph.

**Comment by jvgaultney** [comment]
I though we got rid of live previews. In any case, that layer doesn't seem to be updating properly and often gives different (out of date) dotting patterns.
