### ISSUE TITLE
Guidelines are misaligned with strokes and dots

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#21]
Currently Guidelines are being defined by name, font-wide values in the master. The Thickness is then extended upwards, starting at the named value. But since strokes (and dots) are expanded in both directions, this results in guidelines and strokes that are mismatched, as in:

![image](https://github.com/simoncozens/Dotter/assets/4226750/5e70ddcf-4032-421a-9369-da8171f14405)

There are a few different ways this could be addressed:
- Center Guidelines: Center them on the named height values rather than extend them vertically. This will at least center-align everything consistently. It does mean that thick strokes over thin guidelines will extend on both sides of the guideline, which is not ideal.
- Define many more custom font-wide heights: We would add names heights like “BaselineXL”, “BaselineL”. “BaselineR”, etc. then use these.  We could also center the guidelines on the height value (preferred by me), or just leave the behaviour as is and let the designer tweak it.
- Switch to using instance-specific height values: This would allow us to tweak the guidelines to be in ideal positions, even when the thickness is different from the strokes/dots. We could also center the guidelines on the height value (preferred by me), or just leave the behaviour as is and let the designer tweak it.
- **Add an alignment adjustment option (preferred)**: This would involve adding a alignment preference option to each guideline in each instance. When setting a guideline you would choose the font-wide named value, the thickness, and an alignment chosen from these 7 options:
-- Center (default)
-- Top (top of guideline is at chosen value)
-- Top of stroke (top of guideline is at chosen value + half of stroke width)
-- Top of dot (top of guideline is at chosen value + half of dot width)
-- Bottom (bottom of guideline is at chosen value, this is the current default)
-- Bottom of stroke (bottom of guideline is at chosen value - half of stroke width)
-- Bottom of dot (bottom of guideline is at chosen value - half of dot width)
- Adjust the stroking/dotting algorithm to force the letters into height-limited boxes: This would be a major change in strategy, and require quite a bit of revision to the algorithms. When I looked at this long ago, our current strategy of expanding strokes in all directions won out, and I still agree, so I’d not want us to pursue this.

I’d prefer the alignment adjustment option. I’d be willing to go with switching  to using instance-specific values or defining many more custom font-wide height values. In any case I’d prefer that the default be to use the value to define the center, not the bottom, of the guideline.

**Comment by simoncozens** [comment]
> Switch to using instance-specific height values

This is already possible. The "Height" dropdown can take a number as well as a named metric.

![override](https://github.com/simoncozens/Dotter/assets/106728/aefbdf0b-3183-4ffb-9ed1-57f6d88e3e15)
