### ISSUE TITLE
preventOverlaps not being applied in build

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#4]
It seems that overlap removal is not working in the build, even if "preventOverlaps = 1" is in the fontinfo.plist config data.

**Comment by simoncozens** [comment]
I can't reproduce this; I suspect there may have been some code movement. With `preventOverlaps = 0;`, the letter B in the generated Glyphs file looks like:

<img width="193" alt="Screenshot 2023-12-11 at 15 25 23" src="https://github.com/simoncozens/Dotter/assets/106728/11c19e33-85f2-48d5-8af5-69fc935e5139">

With ` preventOverlaps = 1;`, I get:

<img width="271" alt="Screenshot 2023-12-11 at 15 26 20" src="https://github.com/simoncozens/Dotter/assets/106728/c397d2ac-c93e-41b8-9adb-8b6e32385e96">

Which is not optimal, I admit, but at least it's doing *something*.

**Comment by simoncozens** [comment]
And confirmed, that's what is happening in the latest build. So I think this got fixed somewhere.

**Comment by jvgaultney** [comment]
Not working here. With font-pendot-latin and a newly provisionned venv I still get this:

![image](https://github.com/simoncozens/Dotter/assets/4226750/02e683e8-ab70-4845-b1a2-f372a7971ae4)

The .glyphspackage fontinfo.plist has this:

```
userData = {
co.uk.corvelsoftware.Dotter = {
alternateLayerName = "<null>";
dotSize = 60;
dotSpacing = 40;
endCap = Round;
joinType = Round;
preventOverlaps = 1;
removeExternal = 0;
removeInternal = 0;
segmentWise = 0;
splitPaths = 1;
startCap = Round;
strokerAngle = 0;
strokerHeight = 80;
strokerHeightLock = 1;
strokerWidth = 80;
};
};
```

**Comment by simoncozens** [comment]
Aha! It's about components.
