### ISSUE TITLE
Use named alternate layer for the contour source if glyph exists there

### ISSUE THREAD

**Issue by jvgaultney** [simoncozens/Dotter#7]
Enable the designer to set (in instance custom parameters) a named layer as a source for alternate skeleton sources. If a glyph exists in that layer then the dotter would use that glyph as the source rather than the normal one.

This would allow for instance-specific alterations to the skeletal source that would change the dotted results, much like delta hints. These would then have no impact on other instances or on other operations such as stroking.

**Comment by simoncozens** [comment]
I've done some of the scaffolding for this but before I go any further and plumb it into the interface, I think we need to step back a bit and think about what parameters get stored where; and this is something I would like your involvement in. Currently we are storing the dotter and stroker parameters in the font's top-level, global "user data". But I can see arguments for some or all of the parameters being stored:

* Globally in the font
* At master level (e.g. it may make sense to put the alternate layer name here)
* At "export" (instance) level e.g. different instances will have different stroke thicknesses and dot sizes.
* Per-glyph for overrides for specific glyphs (some may want splitPaths, some may not?)

For reference here are the current set of parameters and their defaults:

```
DOTTER_PARAMS = {
    "dotSize": 15,
    "dotSpacing": 15,
    "preventOverlaps": True,
    "splitPaths": False,
    "alternateLayerName": None,
}
STROKER_PARAMS = {
    "strokerWidth": 50,
    "strokerHeight": 50,
    "strokerAngle": 0,
    "strokerHeightLock": True,
    "startCap": "round",
    "endCap": "round",
    "joinType": "round",
    "removeExternal": False,
    "removeInternal": False,
    "segmentWise": False
}
```

**Comment by jvgaultney** [comment]
Yeah - good question. It might be good for us to talk about this, as I need to understand better how instance definitions in Glyphs relate to config.yaml recipes. We also need to consider how this data would ideally be represented in a UFO+designspace world so we are careful not to make that more difficult. As I understand it, the fundamental difficulty in Glyphs3<>UFO+designspace is the significantly different family structure model.

By "Globally in the font" I think you mean at the top level of the Glyphs file - right? "Font" is potentially confusing. I'm assuming this is what you mean.

Here are my first thoughts on what belongs where in a conceptual, not necessarily actual, hierarchy. Basically it's storing everything in the internal export/instance, but allows a named layer in individual glyphs to be used for alternate data.

- GLYPHSFILE
  - MASTER
    - GLYPH
      - LAYER (SOURCE) - info that is considered permanent and is used in the build
        - Alternate skeletons
        - Override for splitPaths, preventOverlaps
        - Overrides for stroker params?
      - LAYER (PREVIEW) - outlines that are stored for visual review but not used in build
  - EXPORT (INTERNAL) - info that is accessible to Glyphs plugins and applied in preview (instances)
    - Default location for all dotting and stroking params, including alternateLayerName
    - Guideline params, though not used by preview?
- EXPORT (EXTERNAL) - info that may exist externally (recipes)

There are some stroker params that I don't understand, so haven't include those in my thinking (strokerHeightLock, removeExternal, removeInternal, segmentWise). 

Where I'm really unsure of things is related to final .ttf naming (family and file names). I know the recipe deal with this, but I don't know how that relates to individual instance definitions in the Glyphs file. 

Let me know when you'd be available to talk though this.

**Comment by jvgaultney** [comment]
BTW alternateLayerName is definitely needed at the instance level, as different instances (say, with different dot densities) may require different overrides.

**Comment by simoncozens** [comment]
Currently the "thing" we dot is a master, not an instance; the build process:

1. Takes each layer of the font source (corresponding to the outlines for a given master)
2. Obtains parameters from somewhere (currently global, but we want to change that)
3. Replaces the outlines of the layer with a series of dots.
4. Writes a new .glyphs file with these dotted masters.
5. Builds that new .glyphs file to get dotted instances.

But it sounds like we actually want to do dotting a bit further into the build process. (No problem, I *think* we can do this!) Doing the dots on "exports" (instances) would mean we could have separate font binary files with different dot parameters from the same master outlines. I can see that as being desirable.

The way I'm handling this development process is pretty cyclic; we're iterating on different components as we circle towards what we eventually want to see, as that's the best way to firm up the desired user experience and requirements. So we started with a simple interface, then spun off the actual "dotting" part of it to a separate process so we could work on getting a simple build process working; now we need to go back and build out the user interface (making all these decisions  about what information goes where and how best to give the user access to it), and then after that we can pull apart the build process and rebuild it to match what we actually want.

So I shall do some thinking about a new front-end in Glyphs (also bearing in mind the comments in #1 about it not being modal and not really being a filter), and then there will be lots of code movement and things will break, and then we can fix it all again. But we are heading in the right direction. :-)

**Comment by simoncozens** [comment]
This is now done in the Designer, on to the build.
